import { Config } from "../models";

export const game: Config = {
  topic: "events in the Paris 2024 olympics",
  answers: [
    "Archery",
    "Athletics",
    "Badminton",
    "Basketball",
    "Basketball 3x3",
    "Boxing",
    "Canoe slalom",
    "Canoe sprint",
    "Road cycling",
    "Cycling track",
    "Mountain biking",
    "BMX freestyle",
    "BMX racing",
    "Equestrian",
    "Fencing",
    "Football",
    "Golf",
    "Artistic gymnastics",
    "Rhythmic gymnastics",
    "Trampoline",
    "Handball",
    "Hockey",
    "Judo",
    "Modern pentathlon",
    "Rowing",
    "Rugby",
    "Sailing",
    "Shooting",
    "Table tennis",
    "Taekwondo",
    "Tennis",
    "Triathlon",
    "Volleyball",
    "Beach volleyball",
    "Diving",
    "Marathon swimming",
    "Artistic swimming",
    "Swimming",
    "Water polo",
    "Weightlifting",
    "Wrestling",
    "Breaking",
    "Sport climbing",
    "Skateboarding",
    "Surfing",
  ],
};
