import { Config } from "../models";

export const game: Config = {
  topic: "countries",
  answers: [
    "Bonjour",
    "Hola",
    "Ciao",
    "Hallo",
    "Olá",
    "Selam",
    "Namaste",
    "Merhaba",
    "Konnichiwa",
    "Shalom",
    "Anyeonghaseyo",
    "Dia dhuit",
    "Hej",
    "Здравствуйте",
    "Xin chào",
    "Hei",
    "Nǐ hǎo",
    "S̄wạs̄dī",
    "Moien",
    "Sveiki",
    "Ahoj",
    "Privet",
    "Kamusta",
    "Marhaba",
    "Salve",
    "Sveika",
    "Sveiks",
    "Bunâ",
    "Talofa",
    "Thobela",
    "Zdravo",
    "Dumela",
    "Molo",
    "Ia Orana",
    "Li-hó",
    "Vanakkam",
    "Hallo",
    "Përshëndetje",
    "Iwi selami newi",
    "Kamisisaki",
    "Salam",
    "Kaixo",
    "Vitaju",
    "Hyālō",
    "Zdravo",
    "Zdraveĭte",
    "Haallo",
    "Salve",
    "Hola",
    "Bula",
    "Kumusta",
    "Hei",
    "Mba'éichapa",
    "Bonjou",
    "Aloha",
    "Nyob zoo",
    "Szia",
    "Halló",
    "Ndewo",
    "Hello",
    "Halo",
    "Sain uu",
    "Niltze Tialli Pialli",
    "Ya’at’eeh",
    "Namaskāra",
    "Akkam",
    "Allianchu",
    "Sabaidi",
    "Hallå",
    "Bongu",
    "Selamat pagi",
    "Kia ora",
    "Thobela",
    "Bunâ",
    "Nǐ hǎo",
    "Mālō e lelei",
    "Avuxeni",
    "Merhaba",
    "Xin chào",
    "Helo",
    "Malo",
    "Ia Orana",
    "Li-hó",
    "Vanakkam",
  ],
};
